# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 14
      uses: actions/setup-java@v4
      with:
        java-version: '14'
        distribution: 'adopt'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
      with:
        gradle-version: '6.9.4'

    #- name: Clean with Gradle
      #run: ./gradlew clean

    - name: Build with Gradle 6.9.4
      #run: gradle build
      run: ./gradlew build
  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: dja111/wein-service
        tags: ${{ github.event.push.head.sha }}
        registry: docker.io
        dockerfile: deployment/docker/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  #dependency-submission:

    #runs-on: ubuntu-latest
    #permissions:
      #contents: write

    #steps:
    #- uses: actions/checkout@v4
    #- name: Set up JDK 14
      #uses: actions/setup-java@v1
      #with:
        #java-version: '14'
        #distribution: 'adopt'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    #- name: Generate and submit dependency graph
      #uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
